name: THEGIRD
favicon: null
layout_spectrum: 0.6936029333155602
typography_spectrum: 0.8008119962178171
title: THE GIRD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5f5f5f'
    - '#9f9f9f'
    - '#ffffff'
    - '#cfcfcf'
  brandStrength: 0.9797814767807722
  lightness: 0.19522001640871167
  saturation: 0.918210408417508
  rhythmicContrast: 0.3903824519366026
purpose: []
